### ISSUE TITLE
Adding Jump Animation

### ISSUE THREAD

**Issue by Gariot** [Gaurav0/Universal-LPC-Spritesheet-Character-Generator#19]
Hi,

is it possible to add Jump Animations? Would be nice.

**Comment by jrconway3** [comment]
Wrong place for this. You'd best go ask on Open Game Art: https://opengameart.org/

That's where LPC originated at. The original artist who created the base models might be willing to make Jump animations with a commission. Eventually I planned to do it, but didn't get around to it.

The Universal LPC Spritesheet was made to compile a bunch of different LPC sprites, but hasn't been updated in a while. The Generator was designed to let you build a spritesheet from the Universal LPC Spritesheet, but also likewise hasn't been updated in a while. Its possible (I haven't checked) that additional animations have been made at Open Game Art.

**Comment by Gariot** [comment]
Yea, sorry, i realised that too late ^^ Thats why i closed it so quick. Im really sorry.
